#!/bin/bash

# ================= CONFIGURATION =================

# 1. THE SOURCE COLORS (Original Orange)
SOURCE_COLORS=(
    "#c36c2b" # 1. Main
    "#b25020" # 2. Dark
    "#9c3215" # 3. Darker
    "#921507" # 4. Darkest Red
    "#d18b33" # 5. Highlight
    "#ae6531" # 6. Mid
    "#9b4c28" # 7. Mid-Dark
    "#8f391a" # 8. Shadow
    "#b38040" # 9. Muted
    "#7c2e13" # 10. Deep Shadow
)

# 2. THE TARGET PALETTES

# Variant: Blue (Sci-Fi / Tech Blue)
COLORS_BLUE=(
    "#2bc3db"
    "#209ab2"
    "#157c9c"
    "#075292"
    "#33eed1"
    "#318cae"
    "#28739b"
    "#1a5c8f"
    "#40a0b3"
    "#184d5c"
)

# Variant: Green (Forest / Camo)
# Mapped your 5 colors and calculated blends for the gaps.
COLORS_GREEN=(
    "#62b33d" # 1. Main (Your Color)
    "#5c953c" # 2. Dark (Your Color)
    "#417030" # 3. Darker (Your Color)
    "#355d35" # 4. Darkest (Your Color)
    "#7cd156" # 5. Highlight (Calculated: Lighter Leaf Green)
    "#5e9e3e" # 6. Mid (Calculated: Blend of 1 & 2)
    "#4e8236" # 7. Mid-Dark (Calculated: Blend of 2 & 3)
    "#1a4c39" # 8. Shadow (Your Color)
    "#699652" # 9. Muted (Calculated: Desaturated Main)
    "#0f2e22" # 10. Deep Shadow (Calculated: Darker than 8)
)

# Variant: Magenta (Berry / Sunset Gradient)
COLORS_MAGENTA=(
    "#e16971"
    "#c3527e"
    "#9d4387"
    "#8d317e"
    "#f0868e"
    "#d15d77"
    "#b04a82"
    "#7a276d"
    "#cc7a85"
    "#551b4c"
)

# Variant: White (Bright / Clean)
COLORS_WHITE=(
    "#eeeeee"
    "#dcdcdc"
    "#bdbdbd"
    "#9e9e9e"
    "#ffffff"
    "#e0e0e0"
    "#cfcfcf"
    "#bfbfbf"
    "#f5f5f5"
    "#737373"
)

# 3. SETTINGS
# Which variants to generate?
VARIANTS=("blue" "green" "magenta" "white")

FUZZ_AMOUNT="2%"
COMPRESSION_ARGS=("-strip" "-quality" "95")
OUTPUT_DIR="colored"
EXCLUDE_SUFFIX="_glowmask"

# =================================================

# Check if ImageMagick is installed
if command -v magick &> /dev/null; then
    IM_CMD="magick"
elif command -v convert &> /dev/null; then
    IM_CMD="convert"
else
    echo "Error: ImageMagick is not installed."
    exit 1
fi

# Create output directory
if [ ! -d "$OUTPUT_DIR" ]; then
    mkdir -p "$OUTPUT_DIR"
fi

echo "Starting multi-color processing..."

# LOOP 1: Iterate through every PNG file
for img in *.png; do
    
    # Validation checks
    [ -e "$img" ] || continue
    
    # Skip excluded files
    if [[ "$img" == *"${EXCLUDE_SUFFIX}.png" ]]; then
        echo "Skipping glowmask: $img"
        continue
    fi
    
    # Skip files that look like they were generated by this script
    already_processed=false
    for v in "${VARIANTS[@]}"; do
        if [[ "$img" == *"_${v}.png" ]]; then
            already_processed=true
        fi
    done
    if [ "$already_processed" = true ]; then
        continue
    fi

    filename=$(basename "$img" .png)
    echo ">> Source: $img"

    # LOOP 2: Iterate through the requested color variants
    for variant in "${VARIANTS[@]}"; do
        
        # Select the correct target array based on the variant name
        case $variant in
            "blue")
                TARGET_COLORS=("${COLORS_BLUE[@]}")
                ;;
            "green")
                TARGET_COLORS=("${COLORS_GREEN[@]}")
                ;;
            "magenta")
                TARGET_COLORS=("${COLORS_MAGENTA[@]}")
                ;;
            "white")
                TARGET_COLORS=("${COLORS_WHITE[@]}")
                ;;
            *)
                echo "Unknown variant: $variant"
                continue
                ;;
        esac

        output_name="${OUTPUT_DIR}/${filename}_${variant}.png"
        
        # Build arguments
        args=()
        args+=("-fuzz" "$FUZZ_AMOUNT")

        # Loop through indices of the source array
        count=${#SOURCE_COLORS[@]}
        for (( i=0; i<count; i++ )); do
            src="${SOURCE_COLORS[$i]}"
            tgt="${TARGET_COLORS[$i]}"
            
            # Safety check: ensure target exists
            if [ -z "$tgt" ]; then
                echo "Warning: No mapping found for $src in $variant variant"
                continue
            fi

            args+=("-fill" "$tgt" "-opaque" "$src")
        done

        # Add compression
        args+=("${COMPRESSION_ARGS[@]}")

        # Run ImageMagick
        "$IM_CMD" "$img" "${args[@]}" "$output_name"
    done
done

echo "Done! Check the '$OUTPUT_DIR' folder."