plugins {
    id 'com.github.johnrengelman.shadow'
}

architectury {
    platformSetupLoomIde()
    fabric()
}

loom {
    accessWidenerPath.set(project(":common").loom.accessWidenerPath)

    runs {
        create("data") {
            client()
            name("Minecraft Data")
            source("data")

            property("fabric-api.datagen")
            property("fabric-api.datagen.modid", "$archives_name-data")
            property("fabric-api.datagen.output-dir", file("src/main/generated").absolutePath)
            property("fabric-api.datagen.strict-validation")
        }
    }
}

repositories {
    // Additional Entity Attributes (Mythic Metals dependency)
    maven { url = 'https://api.modrinth.com/maven/' }
    // Cardinal Components (Mythic Metals dependency)
    maven { url = 'https://maven.ladysnake.org/releases' }
}

dependencies {
    // Fabric
    modImplementation "net.fabricmc:fabric-loader:$fabric_loader_version"
    // Fabric API
    modImplementation "net.fabricmc.fabric-api:fabric-api:$fabric_api_version"

    // Common
    common(project(path: ':common', configuration: 'namedElements')) { transitive false }
    shadowCommon(project(path: ':common', configuration: 'transformProductionNeoForge')) { transitive false }

    // Architectury API
    modImplementation "dev.architectury:architectury-fabric:$architectury_api_version"
    // Athena (CTM)
    modRuntimeOnly "earth.terrarium.athena:athena-fabric-1.21:4.0.0"
    // Energy API
    include modApi("teamreborn:energy:$reborn_energy_version") { transitive = false }
    // GeckoLib
    modImplementation "software.bernie.geckolib:geckolib-fabric-$minecraft_version:$geckolib_version"
    // Jade
    modImplementation "curse.maven:jade-324717:5639994"
    // Mod Menu
    modImplementation "com.terraformersmc:modmenu:11.0.3"
    // Oracle Index
    modRuntimeOnly "curse.maven:oracle-index-1206582:6538216"
    implementation "org.jsoup:jsoup:1.17.2"
    // owo-lib
    modImplementation "io.wispforest:owo-lib:$owo_version"

    // recipe viewer runtime
    switch (recipe_viewer.toLowerCase(Locale.ROOT)) {
        case "emi": modRuntimeOnly "dev.emi:emi-fabric:$emi_version"; break
        case "rei": modRuntimeOnly "me.shedaniel:RoughlyEnoughItems-fabric:$rei_version"; break
        case "jei": modRuntimeOnly "mezz.jei:jei-$minecraft_version-fabric:$jei_version"; break
        case "disabled": break
        default: println("Unknown recipe viewer specified: $recipe_viewer. Must be EMI, REI, JEI, or disabled.")
    }

    // in-game testing
    modImplementation "curse.maven:reborncore-237903:5608204"
    modImplementation "curse.maven:simple-conveyor-belts-1292980:6721806"
    modImplementation "curse.maven:tags-viewer-1119728:5807898"
    modImplementation "curse.maven:techreborn-233564:5608205"
    
    // datagen
    // Alloy Forgery
    modDataImplementation "curse.maven:alloy-forgery-438718:$alloy_forgery_version_id"
    // Clutter
    modDataImplementation "curse.maven:clutter-826060:$clutter_version_id"
    modDataRuntimeOnly("com.terraformersmc.terraform-api:terraform-wood-api-v1:$project.terraform_wood_api_version") { transitive = false }
    // Energized Power
    modDataImplementation "curse.maven:energized-power-782147:$energized_power_version_id"
    // Mythic Metals
    modDataImplementation "curse.maven:mythicmetals-410127:$mythic_metals_version_id"
    modDataRuntimeOnly("org.ladysnake.cardinal-components-api:cardinal-components-base:$cardinal_components_version") { transitive = false }
    modDataRuntimeOnly("org.ladysnake.cardinal-components-api:cardinal-components-entity:$cardinal_components_version") { transitive = false }
    modDataRuntimeOnly "maven.modrinth:additionalentityattributes:$additional_entity_attributes_version"
}

publishMods {
    file = remapJar.archiveFile
    changelog = file("../CHANGELOG.MD").getText()
    type = BETA
    modLoaders.add("fabric")

    modrinth {
        accessToken = providers.environmentVariable("MODRINTH_API_KEY")
        projectId = "4sYI62kA"
        minecraftVersions.add("1.21.1")
        minecraftVersions.add("1.21")

        requires("owo-lib")
        requires("geckolib")
        requires("athena-ctm")
        requires("fabric-api")
        requires("architectury-api")

        announcementTitle = "Fabric Version on Modrinth"
    }

    curseforge {
        accessToken = providers.environmentVariable("CURSEFORGE_API_KEY")
        projectId = "1030830"
        minecraftVersions.add("1.21.1")
        minecraftVersions.add("1.21")

        requires("owo-lib")
        requires("geckolib")
        requires("athena")
        requires("fabric-api")
        requires("architectury-api")

        javaVersions.add(JavaVersion.VERSION_21)
        clientRequired = true
        serverRequired = true

        projectSlug = "oritech"
        announcementTitle = "Fabric Version on CurseForge"
    }
}

