plugins {
    id 'net.neoforged.moddev' version '2.0.107' apply false
    id 'fabric-loom' version '1.9-SNAPSHOT' apply false
    id "me.modmuss50.mod-publish-plugin" version "0.8.0" apply false
    id 'org.sinytra.wiki.toolkit' version '0.1.16'
}

// all projects including the root project
allprojects {
    apply plugin: 'java'

    base {
        archivesName = "$mod_id-$minecraft_version"
    }

    java {
        withSourcesJar()
        toolchain.languageVersion = JavaLanguageVersion.of(21)
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }
}

// all projects but the root project
subprojects {
    apply plugin: 'maven-publish'

    repositories {
        mavenCentral()
        maven { url = "https://repo.spongepowered.org/repository/maven-public" }
        // EnderIO
        maven { url = 'https://maven.rover656.dev/releases' }
        // owo-lib
        maven { url = 'https://maven.wispforest.io/releases/' }
        // GeckoLib
        maven { url = 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/' }
        // REI
        maven { url = "https://maven.shedaniel.me/" }
        // EMI
        maven { url = 'https://maven.terraformersmc.com/' }
        // Jade
        maven { url = "https://beta.cursemaven.com" }
        // FFAPI
        maven { url = "https://maven.su5ed.dev/releases" }
        // JEI
        maven { url = "https://maven.blamejared.com/" }
        // Athena (CTM)
        maven { url = "https://maven.teamresourceful.com/repository/maven-public/" }
        // Additional Entity Attributes (Mythic Metals dependency)
        maven { url = 'https://api.modrinth.com/maven/' }
        // Cardinal Components (Mythic Metals dependency)
        maven { url = 'https://maven.ladysnake.org/releases' }
    }

    dependencies {
        // Auto Services
        compileOnly "com.google.auto.service:auto-service:$autoServiceVersion"
        annotationProcessor "com.google.auto.service:auto-service:$autoServiceVersion"
    }

    ['apiElements', 'runtimeElements', 'sourcesElements'].each { variant ->
        configurations."$variant".outgoing {
            capability("$group:${base.archivesName.get()}:$version")
            capability("$group:$mod_id-${project.name}-${minecraft_version}:$version")
            capability("$group:$mod_id:$version")
        }
        publishing.publications.configureEach {
            suppressPomMetadataWarningsFor(variant)
        }
    }

    // configure Maven publishing
    publishing {
        publications {
            mavenJava(MavenPublication) {
                artifactId = "${base.archivesName.get()}-${project.name}"
                from components.java
            }
        }
        repositories {
            maven {
                url System.getenv('local_maven_url')
            }
        }
    }
}

// only loader projects
subprojects {
    if (project.path == ":common") {
        return
    }

    apply plugin: 'me.modmuss50.mod-publish-plugin'

    configurations {
        commonJava {
            canBeResolved = true
        }
        commonResources {
            canBeResolved = true
        }
    }

    dependencies {
        compileOnly(project(':common')) {
            capabilities {
                requireCapability "$group:$mod_id"
            }
        }
        commonJava project(path: ':common', configuration: 'commonJava')
        commonResources project(path: ':common', configuration: 'commonResources')
    }

    sourceSets {
        main {
            resources {
                srcDir(file("src/main/generated"))
                exclude("**/.cache")
            }
        }

        create("data") {
            compileClasspath += sourceSets.main.output
            runtimeClasspath += sourceSets.main.output
            compileClasspath += sourceSets.main.compileClasspath
            runtimeClasspath += sourceSets.main.runtimeClasspath
        }
    }

    tasks {
        processResources {
            dependsOn(configurations.commonResources)
            from(configurations.commonResources)
        
            inputs.property 'version', project.version
            filesMatching(['META-INF/neoforge.mods.toml', "fabric.mod.json"]) {
                expand version: version
            }
        }

        named('compileJava', JavaCompile) {
            dependsOn(configurations.commonJava)
            source(configurations.commonJava)
        }

        named('sourcesJar', Jar) {
            dependsOn(configurations.commonJava)
            from(configurations.commonJava)
            dependsOn(configurations.commonResources)
            from(configurations.commonResources)
        }

        //        withType(AbstractCopyTask).configureEach {
        //            duplicatesStrategy = DuplicatesStrategy.EXCLUDE
        //        }
    }
}

// sinytra wiki
wiki {
    docs {
        oritech {
            // path to the folder containing metadata file (sinytra-wiki.json)
            root = file('docs')
            exportedAssetNamespaces = ['oritech']
            wikiAccessToken = System.getenv('WIKI_TOKEN')
        }
    }
}