plugins {
    id 'architectury-plugin' version '3.4-SNAPSHOT'
    id 'dev.architectury.loom' version '1.10-SNAPSHOT' apply false
    id 'com.github.johnrengelman.shadow' version '8.1.1' apply false
    id 'org.sinytra.wiki.toolkit' version '0.1.16'
    id "me.modmuss50.mod-publish-plugin" version "0.8.0" apply false
}

architectury {
    minecraft = minecraft_version
}

// all projects including the root project
allprojects {
    apply plugin: 'java'
    
    java {
        withSourcesJar()
        toolchain.languageVersion = JavaLanguageVersion.of(21)
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }
}

// all projects but the root project
subprojects {
    apply plugin: 'dev.architectury.loom'
    apply plugin: 'architectury-plugin'
    apply plugin: 'maven-publish'
    
    base {
        archivesName = "$archives_name-$project.name"
    }

    loom {
        silentMojangMappingsLicense()
        mixin.useLegacyMixinAp = false
    }

    tasks {
        withType(JavaCompile).configureEach {
            options.encoding = "UTF-8"
            options.release = 21
        }
        withType(GenerateModuleMetadata).configureEach {
            enabled = false
        }
    }
    
    repositories {
        // owo-lib
        maven { url 'https://maven.wispforest.io/releases/' }
        // GeckoLib
        maven { url 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/' }
        // REI
        maven { url "https://maven.shedaniel.me/" }
        // EMI
        maven { url 'https://maven.terraformersmc.com/' }
        // Jade
        maven { url "https://beta.cursemaven.com" }
        // FFAPI
        maven { url "https://maven.su5ed.dev/releases" }
        // JEI
        maven { url = "https://maven.blamejared.com/" }
        // Athena (CTM)
        maven { url "https://maven.teamresourceful.com/repository/maven-public/" }
    }

    dependencies {
        minecraft "net.minecraft:minecraft:$minecraft_version"
        mappings loom.layered {
            officialMojangMappings()
            parchment("org.parchmentmc.data:parchment-$minecraft_version:$parchment_mappings@zip")
        }
        
        // Auto Services
        compileOnly "com.google.auto.service:auto-service:$autoServiceVersion"
        annotationProcessor "com.google.auto.service:auto-service:$autoServiceVersion"
    }

    // Configure Maven publishing.
    publishing {
        publications {
            mavenJava(MavenPublication) {
                artifactId = base.archivesName.get()
                from components.java
            }
        }

        // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
        repositories {
            // Add repositories to publish to here.
            // Notice: This block does NOT have the same function as the block in the top level.
            // The repositories here will be used for publishing your artifact, not for
            // retrieving dependencies.
        }
    }
}

// only loader projects
subprojects {
    if (project.path == ":common") {
        return
    }

    apply plugin: 'com.github.johnrengelman.shadow'
    apply plugin: 'me.modmuss50.mod-publish-plugin'

    sourceSets {
        main {
            resources {
                srcDir(file("src/generated/resources"))
                exclude("**/.cache")
            }
        }

        create("data") {
            compileClasspath += sourceSets.main.output
            runtimeClasspath += sourceSets.main.output
            compileClasspath += sourceSets.main.compileClasspath
            runtimeClasspath += sourceSets.main.runtimeClasspath
        }
    }
    
    loom {
        /**
         * "main" matches the default mod name
         * since `compileOnly()` is being used in Architectury, the local mods for the
         * loaders need to be set up too
         * otherwise, they won't recognize :common.
         */
        mods {
            main {
                sourceSet sourceSets.main
                sourceSet project(":common").sourceSets.main
            }
        }
        
        createRemapConfigurations(sourceSets.data)
    }

    def shadowCommon = configurations.create('shadowCommon')
    configurations {
        common
        shadowCommon
        compileClasspath.extendsFrom common
        runtimeClasspath.extendsFrom common
    }

    components.java.withVariantsFromConfiguration(configurations.shadowRuntimeElements) {
        skip()
    }

    tasks {
        shadowJar {
            exclude "architectury.common.json"
            configurations = [shadowCommon]
            archiveClassifier = "dev-shadow"
        }

        remapJar {
            inputFile = shadowJar.archiveFile
            dependsOn shadowJar
            archiveClassifier = null
            injectAccessWidener = true
        }

        jar {
            archiveClassifier = "dev"
        }

        sourcesJar {
            def commonSources = project(":common").tasks.sourcesJar
            dependsOn commonSources
            from commonSources.archiveFile.map { zipTree(it) }
            archiveClassifier = "sources"
        }

        processResources {
            inputs.property 'version', project.version
            filesMatching(['META-INF/neoforge.mods.toml', "fabric.mod.json"]) {
                expand version: version
            }
        }
    }
}

// sinytra wiki
wiki {
    docs {
        oritech {
            // path to the folder containing metadata file (sinytra-wiki.json)
            root = file('docs')
            exportedAssetNamespaces = ['oritech']
            wikiAccessToken = System.getenv('WIKI_TOKEN')
        }
    }
}