# Mod properties
group = rearth.oritech
archives_name = oritech
version = 0.17.4
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.21.1
parchment_mappings = 2024.11.17

# Loaders
fabric_loader_version = 0.16.14
fabric_api_version = 0.115.6+1.21.1
neoforge_version = 21.1.128

# Common Dependencies
architectury_api_version = 13.0.8
geckolib_version = 4.6.6
owo_version = 0.12.15.4+1.21
owo_neo_version = 0.12.15.1-beta.3+1.21
emi_version = 1.1.22+1.21.1
rei_version = 16.0.754
jei_version = 19.21.0.247

# Fabric Dependencies
reborn_energy_version = 4.1.0

# Fabric Datagen Dependencies
clutter_version_id = 6211358
terraform_wood_api_version = 11.0.0
alloy_forgery_version_id = 5611901
energized_power_version_id = 6341086
mythic_metals_version_id = 6375684
cardinal_components_version = 6.1.0
additional_entity_attributes_version = 1.8.0+1.21

# Recipe Viewer Preference
# Available emi, rei, jei or disabled
recipe_viewer = emi

# Gradle
org.gradle.jvmargs=-Xmx6G
org.gradle.parallel=true