#!/bin/bash

# Define the base content directory
BASE_DIR="./"

# --- THE MASTER ARTICLE LIST ---
# Format: "Filename | Folder | Title | Type | Related_Items_Array"
articles=(
    # --- NUCLEAR & PARTICLE ---
    "accelerator_controller|particle|Accelerator Controller|block|[]"
    "accelerator_motor|particle|Accelerator Motor|block|[]"
    "accelerator_ring|particle|Accelerator Ring|block|[]"
    "accelerator_sensor|particle|Accelerator Sensor|block|[]"
    "particle_collector_block|particle|Particle Collector|block|[]"
    "reactor_controller|nuclear|Reactor Controller|block|[]"
    "reactor_wall|nuclear|Reactor Wall|block|[]"
    "reactor_rod|nuclear|Reactor Rod|block|[]"
    "reactor_double_rod|nuclear|Reactor Double Rod|block|[]"
    "reactor_quad_rod|nuclear|Reactor Quad Rod|block|[]"
    "reactor_vent|nuclear|Reactor Heat Vent|block|[]"
    "reactor_reflector|nuclear|Reactor Reflector|block|[]"
    "reactor_heat_pipe|nuclear|Reactor Heat Pipe|block|[]"
    "reactor_condenser|nuclear|Reactor Condenser|block|[]"
    "reactor_fuel_port|nuclear|Reactor Fuel Port|block|[]"
    "reactor_absorber_port|nuclear|Reactor Absorber Port|block|[]"
    "reactor_energy_port|nuclear|Reactor Energy Port|block|[]"
    "reactor_redstone_port|nuclear|Reactor Redstone Port|block|[]"
    "nuke|nuclear|Nuke|block|[\"oritech:low_yield_nuke\"]"
    "uranium_processing|nuclear|Uranium Materials|block|[\"oritech:uranium_pellet\", \"oritech:uranium_dust\", \"oritech:uranium_ingot\", \"oritech:uranium_gem\"]"
    "particle_collector_block|particle|Particle Collector|block|[]"

    # --- MACHINES ---
    "pulverizer_block|machines|Pulverizer|block|[]"
    "assembler_block|machines|Assembler|block|[]"
    "foundry_block|machines|Foundry|block|[]"
    "centrifuge_block|machines|Centrifuge|block|[]"
    "atomic_forge_block|machines|Atomic Forge|block|[]"
    "refinery_block|machines|Refinery|block|[]"
    "refinery_module_block|machines|Refinery Module|block|[]"
    "deep_drill_block|machines|Deep Drill|block|[]"
    "drone_port_block|machines|Drone Port|block|[]"
    "powered_furnace_block|machines|Powered Furnace|block|[]"
    "shrinker_block|machines|Shrinker|block|[]"
    "charger_block|machines|Charger|block|[]"
    "pump_block|machines|Pump|block|[]"
    "treefeller_block|machines|Treefeller|block|[]"
    "fragment_forge_block|machines|Fragment Forge|block|[]"
    "augment_application_block|machines|Augment Application|block|[]"
    "simple_augment_station|machines|Simple Augment Station|block|[]"
    "advanced_augment_station|machines|Advanced Augment Station|block|[]"
    "arcane_augment_station|machines|Arcane Augment Station|block|[]"
    "enchanter_block|machines|Enchanter|block|[]"
    "enchantment_catalyst_block|machines|Enchantment Catalyst|block|[]"
    "spawner_controller_block|machines|Spawner Controller|block|[]"
    "spawner_cage_block|machines|Spawner Cage|block|[]"
    "fertilizer_block|machines|Fertilizer|block|[]"
    "placer_block|machines|Placer|block|[]"
    "destroyer_block|machines|Destroyer|block|[]"
    "laser_arm_block|machines|Laser Arm|block|[]"
    "cooler_block|machines|Cooler|block|[]"
    "pipe_booster_block|machines|Pipe Booster|block|[]"

    # --- ADDONS ---
    "machine_speed_addon|machines|Speed Addon|block|[]"
    "machine_efficiency_addon|machines|Efficiency Addon|block|[]"
    "machine_ultimate_addon|machines|Ultimate Addon|block|[]"
    "machine_processing_addon|machines|Processing Addon|block|[]"
    "machine_fluid_addon|machines|Fluid Addon|block|[]"
    "machine_yield_addon|machines|Yield Addon|block|[]"
    "machine_capacitor_addon|machines|Capacitor Addon|block|[]"
    "machine_acceptor_addon|machines|Energy Acceptor Addon|block|[]"
    "machine_hunter_addon|machines|Hunter Addon|block|[]"
    "machine_burst_addon|machines|Burst Addon|block|[]"
    "machine_combi_addon|machines|Combi Addon|block|[]"
    "machine_extender|machines|Machine Extender|block|[]"
    "machine_redstone_addon|machines|Redstone Addon|block|[]"
    "machine_silk_touch_addon|machines|Silk Touch Addon|block|[]"
    "machine_inventory_proxy_addon|machines|Inventory Proxy Addon|block|[]"
    "quarry_addon|machines|Quarry Addon|block|[]"
    "capacitor_addon_extender|machines|Capacitor Extender|block|[]"
    "crop_filter_addon|machines|Crop Filter Addon|block|[]"

    # --- POWER & LOGISTICS ---
    "energy_pipe|power|Energy Pipe|block|[\"oritech:framed_energy_pipe\", \"oritech:energy_pipe_duct_block\"]"
    "fluid_pipe|power|Fluid Pipe|block|[\"oritech:framed_fluid_pipe\", \"oritech:fluid_pipe_duct_block\"]"
    "item_pipe|power|Item Pipe|block|[\"oritech:framed_item_pipe\", \"oritech:item_pipe_duct_block\", \"oritech:transparent_item_pipe\"]"
    "superconductor|power|Superconductor|block|[\"oritech:framed_superconductor\", \"oritech:superconductor_duct_block\"]"
    "power_pole_block|power|Power Pole|block|[]"
    "basic_generator_block|power|Basic Generator|block|[]"
    "bio_generator_block|power|Bio Generator|block|[]"
    "fuel_generator_block|power|Fuel Generator|block|[]"
    "lava_generator_block|power|Lava Generator|block|[]"
    "steam_engine_block|power|Steam Engine|block|[\"oritech:steam_boiler_addon\"]"
    "big_solar_panel_block|power|Big Solar Panel|block|[]"
    "advanced_battery|power|Advanced Battery|block|[]"
    "basic_battery|power|Basic Battery|block|[]"
    "large_storage_block|power|Large Storage|block|[]"
    "small_storage_block|power|Small Storage|block|[]"
    "creative_storage_block|power|Creative Storage|block|[]"
    "small_tank_block|power|Small Fluid Tank|block|[]"
    "creative_tank_block|power|Creative Fluid Tank|block|[]"

    # --- BUILDING & DECORATIVE ---
    "tech_door|building|Tech Door|block|[]"
    "tech_lever|building|Tech Lever|block|[]"
    "tech_button|building|Tech Button|block|[]"
    "ceiling_light|building|Ceiling Light|block|[\"oritech:ceiling_light_hanging\"]"
    "metal_beam_block|building|Metal Beam|block|[]"
    "metal_girder_block|building|Metal Girder|block|[]"
    "industrial_glass_block|building|Industrial Glass|block|[]"
    "machine_frame_block|building|Machine Frame|block|[]"
    "unstable_container|building|Unstable Container|block|[]"
    "dubios_container|building|Dubious Container|block|[]"
    "wither_crop_block|building|Wither Crop|block|[]"
    "black_hole_block|building|Black Hole|block|[]"
    "iron_plating|building|Iron Plating|block|[\"oritech:iron_plating_block\", \"oritech:iron_plating_slab\", \"oritech:iron_plating_stairs\", \"oritech:iron_plating_pressure_plate\"]"
    "carbon_plating|building|Carbon Plating|block|[\"oritech:carbon_plating_block\", \"oritech:carbon_plating_slab\", \"oritech:carbon_plating_stairs\", \"oritech:carbon_plating_pressure_plate\"]"
    "nickel_plating|building|Nickel Plating|block|[\"oritech:nickel_plating_block\", \"oritech:nickel_plating_slab\", \"oritech:nickel_plating_stairs\", \"oritech:nickel_plating_pressure_plate\"]"
    "machine_plating|building|Machine Plating|block|[\"oritech:machine_plating_block\", \"oritech:machine_plating_slab\", \"oritech:machine_plating_stairs\", \"oritech:machine_plating_pressure_plate\"]"
    "industrial_paints|building|Industrial Paints|item|[\"oritech:orange_paint\", \"oritech:white_paint\", \"oritech:sculk_paint\", \"oritech:camo_paint\", \"oritech:diamond_paint\", \"oritech:fluxite_paint\", \"oritech:industrial_paint\", \"oritech:netherite_paint\", \"oritech:redstone_paint\"]"

    # --- RESOURCES ---
    "adamant|resources|Adamant|item|[\"oritech:adamant_ingot\", \"oritech:adamant_dust\", \"oritech:adamant_block\"]"
    "biosteel|resources|Biosteel|item|[\"oritech:biosteel_ingot\", \"oritech:biosteel_dust\", \"oritech:biosteel_block\"]"
    "platinum|resources|Platinum|item|[\"oritech:platinum_ingot\", \"oritech:platinum_dust\", \"oritech:platinum_block\", \"oritech:platinum_ore\"]"
    "nickel|resources|Nickel|item|[\"oritech:nickel_ingot\", \"oritech:nickel_dust\", \"oritech:nickel_block\", \"oritech:nickel_ore\"]"
    "electrum|resources|Electrum|item|[\"oritech:electrum_ingot\", \"oritech:electrum_dust\", \"oritech:electrum_block\"]"
    "energite|resources|Energite|item|[\"oritech:energite_ingot\", \"oritech:energite_dust\", \"oritech:energite_block\"]"
    "duratium|resources|Duratium|item|[\"oritech:duratium_ingot\", \"oritech:duratium_dust\", \"oritech:duratium_block\"]"
    "steel|resources|Steel|item|[\"oritech:steel_ingot\", \"oritech:steel_dust\", \"oritech:steel_block\"]"
    "copper|resources|Copper|item|[\"oritech:copper_clump\", \"oritech:copper_dust\", \"oritech:copper_gem\", \"oritech:copper_nugget\"]"
    "iron|resources|Iron|item|[\"oritech:iron_clump\", \"oritech:iron_dust\", \"oritech:iron_gem\"]"
    "gold|resources|Gold|item|[\"oritech:gold_clump\", \"oritech:gold_dust\", \"oritech:gold_gem\"]"
    "fluxite|resources|Fluxite|item|[\"oritech:fluxite_block\"]"
    "biomass|resources|Biomass|item|[\"oritech:biomass_block\"]"
    "plastic|resources|Plastic|item|[\"oritech:plastic_sheet\", \"oritech:plastic_block\"]"
    "uranium_veins|resources|Uranium Veins|block|[\"oritech:uranium_ore\", \"oritech:deepslate_uranium_ore\", \"oritech:uranium_crystal\"]"
    "resource_nodes|resources|Resource Nodes|block|[\"oritech:resource_node_redstone\", \"oritech:resource_node_lapis\", \"oritech:resource_node_iron\", \"oritech:resource_node_coal\", \"oritech:resource_node_gold\", \"oritech:resource_node_emerald\", \"oritech:resource_node_diamond\", \"oritech:resource_node_copper\", \"oritech:resource_node_nickel\", \"oritech:resource_node_platinum\", \"oritech:resource_node_uranium\"]"
    "world_ores|resources|World Ores|block|[\"oritech:nickel_ore\", \"oritech:deepslate_nickel_ore\", \"oritech:deepslate_platinum_ore\", \"oritech:endstone_platinum_ore\"]"

    # --- EQUIPMENT & COMPONENTS ---
    "hand_drill|equipment|Hand Drill|item|[]"
    "chainsaw|equipment|Chainsaw|item|[]"
    "electric_mace|equipment|Electric Mace|item|[]"
    "wrench|equipment|Wrench|item|[]"
    "portable_laser|equipment|Portable Laser|item|[]"
    "target_designator|equipment|Target Designator|item|[]"
    "exo_suit|equipment|Exo Suit|item|[\"oritech:exo_helmet\", \"oritech:exo_chestplate\", \"oritech:exo_leggings\", \"oritech:exo_boots\"]"
    "machine_cores|components|Machine Cores|item|[\"oritech:machine_core_1\", \"oritech:machine_core_2\", \"oritech:machine_core_3\", \"oritech:machine_core_4\", \"oritech:machine_core_5\", \"oritech:machine_core_6\", \"oritech:machine_core_7\"]"
    "magnetic_coil|components|Magnetic Coil|item|[]"
    "motor|components|Motor|item|[]"
    "super_ai_chip|components|Super AI Chip|item|[]"
    "advanced_computing_engine|components|Advanced Computing Engine|item|[]"
    "heisenberg_compensator|components|Heisenberg Compensator|item|[]"
    "clay_catalyst_beads|components|Clay Catalyst Beads|item|[]"
    "polymer_resin|components|Polymer Resin|item|[]"
    "raw_biopolymer|components|Raw Biopolymer|item|[]"
    "unholy_intelligence|components|Unholy Intelligence|item|[]"
    "banana|components|Banana|item|[]"
)

# --- GENERATION ENGINE ---
for entry in "${articles[@]}"; do
    IFS='|' read -r filename folder title type related <<< "$entry"
    mkdir -p "$BASE_DIR/$folder"

    # Write the MDX file
    {
        echo "---"
        echo "id: oritech:$filename"
        echo "type: $type"
        [[ "$related" != "[]" ]] && echo "related_items: $related"
        echo "---"
        echo ""
        echo "# $title"
    } > "$BASE_DIR/$folder/$filename.mdx"

    echo "Generated: [$folder] $filename.mdx"
done