license = "${space_age_mod_license}"

[[mods]]
modId = "${space_age_mod_id}"
version = "${space_age_mod_version}"
displayName = "${space_age_mod_name}"
authors = "rearth"
description = '''
A deeply integrated space-age expansion for Oritech.
'''

[[dependencies.${space_age_mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[${neo_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${space_age_mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${space_age_mod_id}]]
modId = "oritech"
type = "required"
versionRange = "[${oritech_version},)"
ordering = "AFTER"
side = "BOTH"
