architectury {
    common enabled_platforms.split(',')
}

loom.accessWidenerPath.set(file("src/main/resources/${archives_name}.accesswidener"))

dependencies {
    /**
     * loader
     * required here for the @Environment annotations and the mixin dependencies
     * do NOT use other classes from the Fabric loader
     */
    modImplementation "net.fabricmc:fabric-loader:$fabric_loader_version"

    // Architectury API
    modImplementation "dev.architectury:architectury:$architectury_api_version"

    // owo-lib
    modImplementation "io.wispforest:owo-lib:$owo_version"
    annotationProcessor "io.wispforest:owo-lib:$owo_version"

    // GeckoLib
    modImplementation "software.bernie.geckolib:geckolib-common-$minecraft_version:$geckolib_version"

    // EMI
    modCompileOnly "dev.emi:emi-xplat-intermediary:${emi_version}"

    // REI
    modCompileOnly "me.shedaniel:RoughlyEnoughItems-api:$rei_version"

    // JEI
    modCompileOnly "mezz.jei:jei-${minecraft_version}-common-api-intermediary:${jei_version}"

    // Jade (needed for addon)
    modImplementation "curse.maven:jade-324717:5639994"

    // Oracle Index
    modCompileOnly "curse.maven:oracle-index-1206582:6538216"
}

//sourceSets {
//    main {
//        resources.srcDir "src/main/generated"
//        resources.exclude ".cache"
//        // exclude recipes from common because they're loader specific
//        resources.exclude "**/recipe"
//    }
//    fabric {
//        // make recipes available to fabric build
//        resources {
//            srcDir "src/main/generated"
//            include "**/recipe/**"
//        }
//        output.resourcesDir = "data"
//    }
//}

//tasks.withType(AbstractCopyTask).configureEach {
//    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
//}

tasks.named('processResources') {

    from("$rootDir/docs") {
        into "assets/oracle_index/books/oritech"
        exclude '.assets/item/**' // items are rendered in-game as actual item components, no need to include them here
    }

    doLast {
        println "processResources executed: wiki folder copied into assets/oracle_index"
    }
}