plugins {
    id 'net.neoforged.moddev'
}

neoForge {
    // only apply NeoForm to use Vanilla mode (no loader)
    neoFormVersion = "$minecraft_version-$neoform_version"

    validateAccessTransformers = false
    interfaceInjectionData.from file('src/main/resources/interfaces.json').absolutePath
}

// temporary during migration
sourceSets.main.java {
    exclude 'rearth/oritech/init/compat/emi/**'
    exclude 'rearth/oritech/init/compat/jade/**'
    exclude 'rearth/oritech/init/compat/rei/**'
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    sourceSets.main.resources.sourceDirectories.each { dir ->
        commonResources dir
    }
}

dependencies {
    // Architectury API
    compileOnlyApi rootProject.localArchitecturyJar('neoforge')
    // GeckoLib
    compileOnlyApi "com.geckolib:geckolib-neoforge-$minecraft_version:$geckolib_version"
    // JEI
    compileOnly("mezz.jei:jei-${minecraft_version}-common-api:${jei_version}") { transitive = false }
    // Mixin
    compileOnly 'org.spongepowered:mixin:0.8.5'
    compileOnly 'org.ow2.asm:asm-tree:9.8'
    // Mixin Extras
    compileOnly 'io.github.llamalad7:mixinextras-common:0.3.5'
    annotationProcessor 'io.github.llamalad7:mixinextras-common:0.3.5'
    // Forge Config API Port (common module - NeoForge API)
    compileOnlyApi "fuzs.forgeconfigapiport:forgeconfigapiport-common-neoforgeapi:$forge_config_api_port_version"

    // ftb filters
    compileOnly("dev.ftb.mods:ftb-filter-system-neoforge:$ftb_filters_version") { transitive = false }
}
