name: build

# only run on push to 1.21 for relevant files
on:
  push:
    branches:
      - "1.21"
    tags-ignore:
      - "**"
    paths:
      - "gradle/**"
      - "**.java"
      - "**.kts"
      - "**.properties"
      - "**/build.yml"
  pull_request:
    branches:
      - "1.21"
    paths:
      - "gradle/**"
      - "**.java"
      - "**.kts"
      - "**.properties"
      - "**/build.yml"

# cancel previous runs on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: setup jdk 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'
      - name: setup gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-overwrite-existing: true
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build --stacktrace
      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: |
            fabric/build/libs/
            neoforge/build/libs/